/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EventDetailPage: typeof import('./src/components/events/EventDetailPage.vue')['default']
    EventsAdministration: typeof import('./src/components/events/EventsAdministration.vue')['default']
    ExperienceDetail: typeof import('./src/components/experiences/ExperienceDetail.vue')['default']
    ExperiencesAdministration: typeof import('./src/components/experiences/ExperiencesAdministration.vue')['default']
    ExperiencesView: typeof import('./src/components/experiences/ExperiencesView.vue')['default']
    HandleEvents: typeof import('./src/components/events/HandleEvents.vue')['default']
    HandleIt: typeof import('./src/components/itinerary/HandleIt.vue')['default']
    HandleObjectives: typeof import('./src/components/objectives/HandleObjectives.vue')['default']
    HandleObjectiveTypes: typeof import('./src/components/objectives/HandleObjectiveTypes.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItineraryAdministration: typeof import('./src/components/itinerary/ItineraryAdministration.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Map: typeof import('./src/components/map/Map.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ObiectiveTypeAdministration: typeof import('./src/components/objectives/ObiectiveTypeAdministration.vue')['default']
    ObjectiveAdministration: typeof import('./src/components/objectives/ObjectiveAdministration.vue')['default']
    ObjectiveDetailPage: typeof import('./src/components/objectives/ObjectiveDetailPage.vue')['default']
    PhotoCarousel: typeof import('./src/components/PhotoCarousel.vue')['default']
    PhotoGalleria: typeof import('./src/components/PhotoGalleria.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
