/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EventDetailPage: typeof import('./src/components/events/EventDetailPage.vue')['default']
    EventsAdministration: typeof import('./src/components/events/EventsAdministration.vue')['default']
    HandleEvents: typeof import('./src/components/events/HandleEvents.vue')['default']
    HandleObjectives: typeof import('./src/components/objectives/HandleObjectives.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Map: typeof import('./src/components/map/Map.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ObjectiveAdministration: typeof import('./src/components/objectives/ObjectiveAdministration.vue')['default']
    ObjectiveDetailPage: typeof import('./src/components/objectives/ObjectiveDetailPage.vue')['default']
    Password: typeof import('primevue/password')['default']
    PhotoCarousel: typeof import('./src/components/PhotoCarousel.vue')['default']
    PhotoGalleria: typeof import('./src/components/PhotoGalleria.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
  }
}
